### ISSUE TITLE
パッケージ"topicmodels"のインストールができないため、解決策を教えていただきたいです。

### ISSUE THREAD

**Issue by masane** [IshidaMotohiro/RMeCab#17]
お世話になっております、
何度も質問してしまって申し訳ありません。
今度はパッケージのインストールができず困っております。
解決策をご教授いただけますでしょうか。

トピックモデルを作成しようと思い、貴著の記述通り
コンソールに"install.packages("topicmodels")"と実行しましたが
エラーが表示され、うまく導入できていないようです、
以下、エラーメッセージです。

"""
パッケージを ‘/usr/local/lib/R/4.1/site-library’ 中にインストールします 
 (‘lib’ が指定されていないため) 
 URL 'https://cran.rstudio.com/src/contrib/topicmodels_0.2-12.tar.gz' を試しています 
Content type 'application/x-gzip' length 706306 bytes (689 KB)
==================================================
downloaded 689 KB

* installing *source* package ‘topicmodels’ ...
** package ‘topicmodels’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -I"/usr/local/Cellar/r/4.1.1/lib/R/include" -DNDEBUG   -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/xz/include -I/usr/local/include   -fPIC  -Wno-implicit-function-declaration  -c cokus.c -o cokus.o
clang -I"/usr/local/Cellar/r/4.1.1/lib/R/include" -DNDEBUG   -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/xz/include -I/usr/local/include   -fPIC  -Wno-implicit-function-declaration  -c common.c -o common.o
clang -I"/usr/local/Cellar/r/4.1.1/lib/R/include" -DNDEBUG   -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/xz/include -I/usr/local/include   -fPIC  -Wno-implicit-function-declaration  -c ctm.c -o ctm.o
ctm.c:29:10: fatal error: 'gsl/gsl_rng.h' file not found
#include <gsl/gsl_rng.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [ctm.o] Error 1
ERROR: compilation failed for package ‘topicmodels’
* removing ‘/usr/local/lib/R/4.1/site-library/topicmodels’
Warning in install.packages :
  installation of package ‘topicmodels’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/5f/x34qwzf905501tdcsfsh7_th0000gn/T/RtmpYnUZSm/downloaded_packages’
"""

「installation of package ‘topicmodels’ had non-zero exit status」
を手がかりに自力で調べてみましたが、私と同様の事象に対する解決策を見つけることができませんでした。
お忙しいところ申し訳ありませんが、よろしくお願いいたします。
ちなみに同時にインストールするようにとされていた"lda"パッケージは
無事にインストールできております。

**Comment by IshidaMotohiro** [comment]
利用されているのは MacOSX だと思われますが、topicmoldesをインストールしようとすると、コンソールで「 source からインストールするかどうか」尋ねられると思うのですが、その際 N と入力して、バイナリからインストールできませんか？

ちなみにM1 (Silicon) Mac に、M1用のRをインストールした環境でしょうか？

**Comment by masane** [comment]
お返事ありがとうございます。
もう一度"install.package("topicmodels")"を実行してみましたが、
「 source からインストールするかどうか」確認される過程は経ず、
>ctm.c:29:10: fatal error: 'gsl/gsl_rng.h' file not found
#include <gsl/gsl_rng.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [ctm.o] Error 1
・
・
・
以下同文

といったメッセージが表示されます。

はい、M1用のRをインストールして使っております。

**Comment by IshidaMotohiro** [comment]
私のM1 Mac上でM1用R(pkgからインストール)を使うと、sourceではなく、以下のようにバイナリファイルがデフォルトでインストールされます。
<img width="646" alt="スクリーンショット 2021-12-20 16 52 13" src="https://user-images.githubusercontent.com/8279776/146732476-cf9c4223-c5e1-4759-b17b-c6de32f7c30b.png">
ちなみに以下のようにしてインストールできないでしょうか・

`install.packages("topicmodels", type ="binary")`

前にもggplot2で日本語フォントが表示されない件でご相談いただきました。その際も思ったのですが、今回も、どうも通常のMacでの挙動や反応ではなく、Linux(Ubuntu)系統でよく見かける挙動（エラー）のように感じます。
 なにか、心当たりはありませんでしょうか？

**Comment by masane** [comment]
夜分遅くに失礼します！
"install.packages("topicmodels", type ="binary")"でも実行できず、
もう一度色々と調べながらチャレンジした結果、無事インストールすることができました！

方法としては
①Homebrewで自分でgslをインストール、
②ホームディレクトリ下に「.R」ディレクトリを作成、
③terminalで"% vi ~/.R/Makevars"を実行、
④PKG_LIBS=-L/usr/local/opt/gettext/lib
CFLAGS=-I/usr/local/opt/gsl/include
LDFLAGS=-L/usr/local/opt/gsl/lib -lgsl -lgslcblasと記入・保存、
⑤再度" install.packages("topicmodels")"を実行、
といった流れでした。
解決のためにご尽力いただいて本当にありがとうございます。

Rのインストールはhomebrew経由で行ったのですが、
何か関係があったりしますでしょうか？

**Comment by IshidaMotohiro** [comment]
HomeBrewは基本的にソースコードをダウンロードし、ビルドしてインストールする管理システムなので、homebrewでRを入れると、CRANで配布されているRのバイナリ版とはライブラリの依存関係が異なります。

　Macであっても、基本的にLinux (Ubuntu)でソースからインストールしたのと同じ状態になり、新規にパッケージをインストールする場合、今回のように自身で依存関係を満たすよう、関連ライブラリやヘッダファイルを導入することになります。
