### ISSUE TITLE
R及びRStudioにRMeCabのパッケージがインストールされない。

### ISSUE THREAD

**Issue by szkngsk** [IshidaMotohiro/RMeCab#18]
質問失礼致します。
バージョンが変わっていた為Rをインストールし直したところ、RMeCabのパッケージが消失してしまいました。
Macbook Proを使用しており、再度ターミナル経由でMeCabをインストールしましたが、Rに
install.packages("RMeCab", repos = "https://rmecab.jp/R")及び
install.packages("RMeCab", repos = "https://rmecab.jp/R", type = "source") 
を実行しても以下のメッセージが表示されパッケージをインストール出来ません。

ーーーーー
> install.packages("RMeCab", repos = "https://rmecab.jp/R", type = "source")
 警告:  unable to access index for repository https://rmecab.jp/R/src/contrib:
   URL 'https://rmecab.jp/R/src/contrib/PACKAGES' を開けません 
 警告メッセージ: 
package ‘RMeCab’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
ーーーーー

どう対処すればよろしいでしょうか？
何卒よろしくお願い申し上げます。

**Comment by IshidaMotohiro** [comment]
環境を教えて頂けますと幸いです。たとえば
MacOS Monterey Intel版MacBookPro に、
R-4.1.2.pkg をインストール
などの情報を頂きたいです。

**Comment by szkngsk** [comment]
ご返信ありがとうございます。

MacOS High Sierra版MacBookPro（バージョン10.13.6）
R-4.1.2.pkg
RStudio-2021.09.1+372
をインストールしております。

**Comment by IshidaMotohiro** [comment]
確認しました。これはMacOSの特定のバージョンで、現在、ファイルをダウンロードするライブラリ curl が機能していないからではないでしょうか。
いま、関連情報を見つけ出せないのですが、確か昨年、MacOS の libcurl に深刻な脆弱性が確認されましたが、macOS High Sierra 10.13.6 およびそれ以前のバージョンについて、Apple社はアップデートをもはや対応していないのではないでしょうか？（ただし、私の方で確認できていません。）

最良の対処方法はMojave 以降にアップデートすることだと思います。

が、お勧めはしませんが、バイナリなりソースなりをローカルにダウンロードし、インストールすることは可能だと思われます（手もとのHighSierraマシンではインストールできました）。

最新のブラウザを使って
https://rmecab.jp/R/bin/macosx/contrib/4.1/RMeCab_1.07.tgz
あるいは
https://rmecab.jp/R/src/contrib/RMeCab_1.07.tar.gz
をダウンロードし、RStudio右下のPackagesペインで Install ボタンを押し、install from で tgz　ないし tar.gz を選択する。

**Comment by szkngsk** [comment]
ありがとうございます。
新しいOSをインストールする容量が不足していたため、
macOS Monterey版MacBookAirに
R-4.1.2-arm64.pkgを
インストールしました。

そして、MeCabをダウンロード・インストールするためにターミナルを用いて、
xcode-select --install
を入力するところまでは上手くいきましたが、
ーーーーー
cd ~/Downloads  
curl -fsSL ‘https://drive.google.com/uc?
export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE’ -o 
mecab-0.996.tar.gz 
 tar xf mecab-0.996.tar.gz  cd mecab-0.996  
./configure –with-charset=utf8  
make  sudo make install
ーーーーー
と入力すると、
ーーーーー
cd ~/Downloads<2028> curl -fsSL ‘https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE’ -o mecab-0.996.tar.gz<2028> tar xf mecab-0.996.tar.gz<2028> cd mecab-0.996<2028> ./configure –with-charset=utf8<2028> make<2028> sudo make install
[1] 3247
zsh: no matches found: ‘https://drive.google.com/uc?export=download
[1]  + exit 1     cd ~/Downloads  curl -fsSL ‘https://drive.google.com/uc?export=download
zsh: command not found: -o
ーーーーー
と表示され、パスワードを求められることがありません。


この場合、どう対処すればよろしいでしょうか？

**Comment by IshidaMotohiro** [comment]
私のサイトからコピーペーストしてくださったのだと思いますが、実は、サイトの表示だと、引用符がシングルコーテーションではなく、アポストロフィに変わってしまっているのだと思います。

以下の httpsの直前のシングルコーテーションと、そのURLの最後 TFaRUE' の直後のシングルコーテーションを、いったん手作業で消し、改めて半角シングルコーテーション(ダブルコーテーションでも可)に直して試してみてください。辞書の方も、URLの前後のアポストロフィをシングルコーテーションに変えてください。

```
curl -fsSL 'https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE' -o mecab-0.996.tar.gz
curl -fsSL 'https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7MWVlSDBCSXZMTXM' -o mecab-ipadic-2.7.0-20070801.tar.gz
```
