### ISSUE TITLE
RMeCabFreqのTerm表記の変更方法

### ISSUE THREAD

**Issue by ajarnito** [IshidaMotohiro/RMeCab#19]
いつもたいへんお世話になっております。

日本語のテキストをRMeCabFreqで出力すると，Termの表記がすべてカタカナになってしまいます。
漢字かなまじり表記で出力されるようにしたいのですが，どのようにすればよいでしょうか。
辞書はunidic-mecab-2.1.2を使用しております。

別のパソコンでRMeCabとRMeCabUniを使わせていただいておりますが，RMeCabUniがインストールされているとTermは漢字かなまじり表記で出力されます。

お手数をおかけいたしますが，御教示を賜れると幸いです。
どうぞよろしくお願い申しあげます。

---

sessionInfoは下記のとおりです。

R version 4.1.2 (2021-11-01)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.0.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.2 tools_4.1.2

**Comment by IshidaMotohiro** [comment]
ご質問の件ですが、「unidic-mecab をインストールし、RMeCab::RMeCabFreqを使うと、Termの表記がすべてカタカナになってしまう」ということでしょうか。

unidic-mecab については、RMeCabUni を使っていただくことを想定しています。

ただ、RMeCabUni については、アップデートを怠っており、現在（あるいは次期バージョン）の R だと、想定通りに動かないのではないかと想像しています。時間的余裕ができれば、アップデートなりの対応をしたいとは考えているのですが。

**Comment by ajarnito** [comment]
はい，おっしゃるとおりです。
M1 Macにはインストールできません。

RMeCab::RMeCabFreqを使い，Termがすべてカタカナにならないようにする方法はありますでしょうか。
辞書はUniDicを使いたいので，unidic-mecabではなくUniDicをあらためてインストールすればよいでしょうか。

RMeCabUniが使えるパソコンがあとどれくらい動いてくれるか不安なもので，RMeCab::RMeCabFreqを使い，Termがすべてカタカナにならないようにする方法について，お手数ですが御教示を賜れますと幸いです。

**Comment by IshidaMotohiro** [comment]
念のため、M1Macに以下の方法で、RMeCabUniをインストールできないか、お試し頂けないでしょうか。ただ、私の方では確認できておらず、失敗する可能性があるとは思います。

```
install.packages("remotes")
remotes::install_github("IshidaMotohiro/RMeCabUni")
```

**Comment by ajarnito** [comment]
ダメでした…
念のため，下記に結果を貼り付けます。


```
> install.packages("remotes")
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.1/remotes_2.4.2.tgz'
Content type 'application/x-gzip' length 398019 bytes (388 KB)
==================================================
downloaded 388 KB


The downloaded binary packages are in
	/var/folders/6x/dxw38h8933b1rts0tg7lkz100000gn/T//RtmpUrVF9F/downloaded_packages
> remotes::install_github("IshidaMotohiro/RMeCabUni")
Downloading GitHub repo IshidaMotohiro/RMeCabUni@HEAD
✓  checking for file ‘/private/var/folders/6x/dxw38h8933b1rts0tg7lkz100000gn/T/RtmpUrVF9F/remotes1546154949aa6/IshidaMotohiro-RMeCabUni-076d67a/DESCRIPTION’ ...
─  preparing ‘RMeCabUni’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘RMeCabUni_0.03.tar.gz’
   
* installing *source* package ‘RMeCabUni’ ...
** using staged installation
** libs
Error: C++98 standard requested but unsupported
* removing ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/RMeCabUni’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/6x/dxw38h8933b1rts0tg7lkz100000gn/T//RtmpUrVF9F/file154611671715f/RMeCabUni_0.03.tar.gz’ had non-zero exit status
```

**Comment by IshidaMotohiro** [comment]
了解しました。お手間をおかけしました。おかげさまで修正すべきポイントは把握できました。

いま本業の関係で、こちらに着手する余裕がなく、当面、お役に立てそうにないのですが、時間をひねり出して対応したいと考えています。

UniDicのかわりにはならないかと思うのですが、neologd の方でしたら、現行のRMeCabでも（MacないしLinuxであれば）利用可能ですので、あるいはご検討いただければと思います。 https://rmecab.jp/new/  のページ最後

**Comment by ajarnito** [comment]
御教示下さり，どうもありがとうございます。
neologdも検討してみます。
先生にはこれまでも「アールメカブ」掲示板で御教示を賜り，本当に感謝しております。
今後ともどうぞよろしくお願い申しあげます。

**Comment by IshidaMotohiro** [comment]
こちらこそ、当座、お役に立つことができず、申し訳ないです。少しお時間をいただければと思います。よろしくお願いします。
