### ISSUE TITLE
旧バージョン

### ISSUE THREAD

**Issue by ajarnito** [IshidaMotohiro/RMeCab#23]
いつもたいへんお世話になっております。

もし可能でしたら，RMeCabの旧バージョン(例：RMeCab ver. 1.04)をインストールしたいのですが，どのような方法があるでしょうか。

御教示のほど，どうぞよろしくお願い申しあげます。

**Comment by IshidaMotohiro** [comment]
rmecab.jp/R 配下のパッケージ用ディレクトリから直リンで取得頂くことになるかなと思いますが、ディレクトリ構成をCRAN指定の構成にしているので、やや複雑です。想定されているOSと、Rのバージョンについて、お教え頂けますか？

**Comment by ajarnito** [comment]
御返信を下さりどうもありがとうございます。
OSとRのバージョンは下記のとおりです。

macOS High Sierra (10.13.6)
R 3.6.3

お手数をおかけいたしますが，御教示のほどどうぞよろしくお願い申しあげます。
(「パッケージ用ディレクトリから直リンで取得」というのはこれまでやったことがないので不安ですが，どうしても旧バージョンをインストールしたいのでやってみます。)

**Comment by IshidaMotohiro** [comment]
いま High Sierra  からインターネットへのアクセスは可能なんでしょうか？

可能であり、Xcode command Line Toolが入っているのであれば、以下を試してみてください。

```
url <- "http://rmecab.jp/R/src/contrib/RMeCab_1.04.tar.gz"
install.packages(url, repos=NULL, type="source")
```

Xcodeのツールがない場合は以下を試しください。

```
url <- "http://rmecab.jp/R/bin/macosx/el-capitan/contrib/3.6/RMeCab_1.04.tgz"
install.packages(url, repos=NULL, type="binary")
```

インターネットに接続できないのであれば、別マシンで上のURLからダウンロードして、対象マシンに保存し、以下を実行します。

`install.packages("ダウンロードしたファイルへのパスとファイル名", repos=NULL)`

ただ、私もこうした作業を最近は行ったことがなく、かつ High Sierra はサポートも終了している古いOSなので、動作するのか、確信はないです。

**Comment by ajarnito** [comment]
御教示下さり，どうもありがとうございます。

Xcode command Line Toolは入っておりますので，最初の御教示をやってみました。RMeCab(ver.1.04)を無事インストールすることができました。

どうもありがとうございます。
