### ISSUE TITLE
辞書の整備について

### ISSUE THREAD

**Issue by Kazuki-Isomura** [IshidaMotohiro/RMeCab#27]
磯村和樹と申します。もう覚えておられないかもしれませんが、以前、東日本大震災被災地の住民証言分析をRMeCabで行っていた際、石田先生にメールで問い合わせにご対応いただいたことがございます。その節は誠にありがとうございました。

RMeCabのHPを確認していた際、こちらから問合せを、と記載があり、今回はこちら（GitHub）から問合せております。

もう一度RMeCabを用いた分析をしようとしております。
ほとんどの操作は、「Rによるテキストマイニング第2版」の通りに行うことができたのですが、p.20-23の辞書の整備だけうまくいきません。
コマンドプロンプトでは、done!と表示されたのですが、その後docDF()を実行してみても、下記のようになり「基広」となりませんでした。

  TERM   POS1     POS2 Row1
1   基   名詞 固有名詞    1
2 広い 形容詞     自立    1
3 石田   名詞 固有名詞    1

こちらで行った作業と作成したcsvとdicデータをお送りいたしますので、間違った箇所がないかみていただけないでしょうか？

お手数をおかけし大変恐縮ですが、何卒よろしくお願いいたします。

　↓↓↓↓

＜作業＞
・↓のURLのCSVデータをエクセルで作成
・CSVデータをC:\R\Practice\practicejisyo に保存。
・コマンドプロンプトで下記のように入力（done！とは表示される）

C:\Users\lskaz>cd /d C:\Program Files\MeCab\bin
C:\Program Files\MeCab\bin>mecab-dict-index.exe -d "c:\Program Files\MeCab\dic\ipadic" -u c:\R\Practice\practicejisyo\motohiro.dic -f utf-8 -t utf-8 c:\R\Practice\practicejisyo\motohiro.csv
＊MeCabのフォルダはなぜかインストールした際から(x86)でない方のフォルダになっており、そちらとしております
＊csvとdicの保存場所はこちらで作ったフォルダに入れております。
＊RMeCab HPにSHIFT-JISでなくUTF-8でと記載があったので、そのようにしております。

・下記を実行してみたのですが、上記の結果となりました。
(docDF(data.frame(X = "石田基広"), "X", type = 1,
       dic = "C:/R/Practice/practicejisyo/motohiro.dic"))

＜作成したデータ＞
https://drive.google.com/drive/folders/1XFOq9GVkCobKpYkTL6LbRCqiXXcYZ5FH?usp=sharing

**Comment by IshidaMotohiro** [comment]
大変恐縮ですが、見落としおりまして、今日、ご投稿に気が付きました。
確認したところ、WindowsではMeCab本体がユーザー辞書の指定を無視してしまうようで、いまのところ、対策が思いつきません。少し調べてみます。

**Comment by IshidaMotohiro** [comment]
正確には正規のMeCabではなく、フォークされた64bit版のMeCabの挙動ということになります。
https://github.com/ikegami-yukino/mecab/releases/

**Comment by Kazuki-Isomura** [comment]
お忙しい中、ご確認ありがとうございます。もし何か対策が分かりましたら、ご教示いただけましたら幸いです。

**Comment by IshidaMotohiro** [comment]
本件ですが、私がWindowsに慣れていないもので原因に思い当たるのに時間がかかりました。
辞書がファイルの文字コードが BOM付きUTF-8になっていないでしょうか。
一度、メモ帳で開き、単にUTF-8を指定して、保存し、辞書を作成したところ、辞書を指定することができました。

<img width="709" alt="スクリーンショット 2024-05-18 153023" src="https://github.com/IshidaMotohiro/RMeCab/assets/8279776/ed47627e-7bc7-43e9-9416-9fb08438cd9b">

"C:\Program Files\MeCab\bin\mecab-dict-index.exe" -d "c:\Program Files\MeCab\dic\ipadic" -u e:\R\bom.dic -f utf-8 -t utf-8 e:\R\bom.csv

<img width="358" alt="スクリーンショット 2024-05-18 153127" src="https://github.com/IshidaMotohiro/RMeCab/assets/8279776/3c333aac-f5f7-4ff0-80c2-a4b6a3d9d0f5">

**Comment by Kazuki-Isomura** [comment]
ありがとうございます！試してみます。
