### ISSUE TITLE
インストールに失敗し、unlist(res)が解析結果を返さない問題

### ISSUE THREAD

**Issue by daisukeadachi** [IshidaMotohiro/RMeCab#32]
[RMeCaB](https://rmecab.jp/wiki/index.php?RMeCab)のホームページ等に従い、以下の手順でMeCabとRMeCabの導入を試みましたが、unlist(res)が解析結果を返しません。以下実行手順です。

環境:
Mac M1, 2020
Sonoma 14.4.1

1. ターミナルにて以下を実行
`brew install mecab`
`brew install mecab-ipadic`

2. RStudio (2024.04.0+735)にて以下を実行
`install.packages("RMeCab", repos = "http://rmecab.jp/R")`
`library(RMeCab)`
`res <- RMeCabC("すもももももももものうち")`
`unlist (res)`

上記の最終ステップ `unlist (res)` において、以下の結果を返します。

>           \xb5\xad\xb9\xe6 
> "すもももももももものうち" 

これは上記ホームページにおける挙動と異なっておりますが、エラーメッセージ等が表示されず、原因が特定できません。問題の所在、解決策などについてご教示頂けますと幸いです。

**Comment by IshidaMotohiro** [comment]
brew の mecab （の辞書）が、macOS 14 Sonoma (arm64/Apple Silicon) 上で文字化けを起こすという報告があります。

https://github.com/Homebrew/homebrew-core/issues/171137

上記Issueの下の方に、さしあたりの対応策が記載されています。試してみていただけますか？。

**Comment by daisukeadachi** [comment]
ありがとうございます。以下のステップを試してみましたが、先述と同様の結果が出てうまくいきません。

1. インストールされた辞書を（おそらく）過去のMacOSバージョンの辞書と置き換えるため、ターミナル上で以下を実行。
brew uninstall mecab-ipadic
brew fetch --os=big_sur mecab-ipadic
brew install "$(brew --cache --os=big_sur mecab-ipadic)"

2. 先述と同様のコマンドをRStudio上で実行。

コメントや、何か他のアイデアはありますでしょうか。よろしくお願いいたします。

**Comment by IshidaMotohiro** [comment]
Rではなく、Macのターミナルを起動して以下を実行した場合の出力を教えてください。

echo "すもももももももものうち" | mecab

**Comment by daisukeadachi** [comment]
ありがとうございます。こちらは正常な結果を返すようです：

> % echo "すもももももももものうち" | mecab
> すもも	名詞,一般,*,*,*,*,すもも,スモモ,スモモ
> も	助詞,係助詞,*,*,*,*,も,モ,モ
> もも	名詞,一般,*,*,*,*,もも,モモ,モモ
> も	助詞,係助詞,*,*,*,*,も,モ,モ
> もも	名詞,一般,*,*,*,*,もも,モモ,モモ
> の	助詞,連体化,*,*,*,*,の,ノ,ノ
> うち	名詞,非自立,副詞可能,*,*,*,うち,ウチ,ウチ
> EOS

**Comment by IshidaMotohiro** [comment]
私の環境は、Sonoma 14.4.1,R-4.4.0 なのですが、mecabをbrewではなくソースからインストールしており、文字化けは生じていないので、brewのmecab辞書の問題ではないかと思っているのですが、あとでbrewで検証してみます。

**Comment by daisukeadachi** [comment]
ありがとうございます。伝え忘れておりましたが、私のRバージョンも4.4.0です。FYI.
