### ISSUE TITLE
R-4.4.0へのインストール

### ISSUE THREAD

**Issue by hori-k** [IshidaMotohiro/RMeCab#33]
下記の環境でインストールを試みたところ、途中で添付ファイルのようなエラーが出てしまいます。
（RやRStudioのコンソールでは出力が得られれなかったため、ターミナルからRを立ち上げて実行しています。）
お手数をおかけして大変恐れ入りますが、ご確認のほど、よろしくお願いいたします。

[rmecab_install_log.txt](https://github.com/user-attachments/files/15801061/rmecab_install_log.txt)

当方の環境： MacBook Air (2024) M3チップ Sonoma 14.5

> sessionInfo()
R version 4.4.0 (2024-04-24)
Platform: aarch64-apple-darwin20
Running under: macOS Sonoma 14.5

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] ja_JP.UTF-8/ja_JP.UTF-8/ja_JP.UTF-8/C/ja_JP.UTF-8/ja_JP.UTF-8

time zone: Asia/Tokyo
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] processx_3.8.4 compiler_4.4.0 R6_2.5.1       tools_4.4.0    remotes_2.5.0 
[6] callr_3.7.6    ps_1.7.6       pkgbuild_1.4.4
>

**Comment by IshidaMotohiro** [comment]
本件、ご連絡ありがとうございます。

調べたところ、‘MacOSX14.sdk’ `および ‘MacOSX15.sdk’では、RMeCabのC/C++のソースを書き換える必要があるようです。
ただ、いまあまり余裕がないため、対応は少し先に回したいと考えています。

なお、現在公開しているMac用バイナリは、 ‘MacOSX13sdk’ でビルドしていますが、Mac R version 4.4.0 macOS Sonoma 14.5 でも動作するようなので、当面、以下のようにインストールして利用していただきたいと考えます。

` install.packages("RMeCab", repos = "https://rmecab.jp/R")
`

**Comment by hori-k** [comment]
ご確認いただき、ありがとうございます。
ご提示いただいたスクリプトですとダウンロードするのみでしたので、`type = "source"`を追加したところ、最初の投稿と同じエラーが出ました。
ですが、例えば`destdir = "~/Downloads"`と指定して、ローカルにダウンロードしたソースファイルから`install.packages("~/Downloads/RMeCab_1.13.tgz", repos = NULL, type = "source")`でインストールすることができました。

**Comment by IshidaMotohiro** [comment]
応急措置的なのですが、Mac Xcode vers.15 でビルドが通るように修正し、rmeca.jp/Rのほうにアップロードしました。ちょっと、これで様子を見ます。

**Comment by hori-k** [comment]
上記の環境＋別のMac（IntelMac）でも`install.packages("RMeCab", repos = "https://rmecab.jp/R", type = "source")`でインストールすることが出来ました。お忙しい中、早急にご対応いただき、誠にありがとうございます。
