### ISSUE TITLE
Windows installation failing

### ISSUE THREAD

**Issue by DrMaphuse** [IshidaMotohiro/RMeCab#5]
Hi! I'm trying to install your package on Windows, but I always get the following error:

```
C:/Rtools/mingw_32/bin/../lib/gcc/i686-w64-mingw32/4.9.3/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lmecab
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'RMeCab'
```
Not sure if this is an issue with the source code or with my machine - I'd be happy if you could look into it.

**Comment by IshidaMotohiro** [comment]
if you try to install RMeCab from source on Windows, you need libmecab.dll, which  I did not put here.
But I have Windows binary version of RMeCab.
Please run this code in R, if you have already installed MeCab(with Shift Jis) http://taku910.github.io/mecab/ 

> install.packages('RMeCab", repos = "http://rmecab.jp/R")
