### ISSUE TITLE
Installation of RMeCab in RStudio failed

### ISSUE THREAD

**Issue by NbtKmy** [IshidaMotohiro/RMeCab#6]
Hallo
I tried to install RMeCab in Rstudio. I used the line
  install.packages("RMeCab", resos = "http://rmecab.jp/R")

But then the following message appeared:
Warning in install.packages :
  package ‘RMeCab’ is not available (for R version 3.5.1)

I have R vers. 3.5.1 - Should I reinstall the version 3.5, or Do you have other solution maybe?
Thank you

Best regards

**Comment by IshidaMotohiro** [comment]
Please replace '"resos" with "repos"  and rerun

> install.packages('RMeCab", repos = "http://rmecab.jp/R")

**Comment by NbtKmy** [comment]
Many thanks for the reply! I‘m sorry, next time I‘ll check the line more carefully...
